BEGIN;

CREATE TABLE IF NOT EXISTS public.schema_migrations (
    version text PRIMARY KEY,
    applied_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.section_table_permissions (
    section_key text NOT NULL,
    table_name text NOT NULL,
    can_select boolean NOT NULL DEFAULT true,
    can_insert boolean NOT NULL DEFAULT false,
    can_update boolean NOT NULL DEFAULT false,
    can_delete boolean NOT NULL DEFAULT false,
    PRIMARY KEY (section_key, table_name)
);

CREATE TABLE IF NOT EXISTS public.inventory_movements (
    movement_id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_kind text NOT NULL
        CHECK (inventory_kind IN ('raw_material', 'finished_goods', 'furnace_oil')),
    lot_id integer REFERENCES public.raw_material_inventory(lot_id),
    bundle_id integer REFERENCES public.finished_goods_inventory(bundle_id),
    batch_id text REFERENCES public.production_batch(batch_id),
    packing_list_id integer REFERENCES public.packing_list(packing_list_id),
    quantity_delta numeric(14, 4) NOT NULL CHECK (quantity_delta <> 0),
    unit text NOT NULL CHECK (unit IN ('kg', 'litre', 'piece')),
    movement_type text NOT NULL,
    source_type text,
    source_id text,
    idempotency_key text NOT NULL UNIQUE,
    actor_employee_id text REFERENCES public.employees(employee_id),
    occurred_at timestamptz NOT NULL DEFAULT now(),
    reason text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    CHECK (
        (inventory_kind = 'raw_material' AND lot_id IS NOT NULL AND bundle_id IS NULL)
        OR (inventory_kind = 'finished_goods' AND bundle_id IS NOT NULL AND lot_id IS NULL)
        OR (inventory_kind = 'furnace_oil' AND lot_id IS NULL AND bundle_id IS NULL)
    )
);

CREATE INDEX IF NOT EXISTS idx_inventory_movements_lot_time
    ON public.inventory_movements (lot_id, occurred_at DESC)
    WHERE lot_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_inventory_movements_bundle_time
    ON public.inventory_movements (bundle_id, occurred_at DESC)
    WHERE bundle_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_inventory_movements_kind_time
    ON public.inventory_movements (inventory_kind, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_movements_source
    ON public.inventory_movements (source_type, source_id)
    WHERE source_type IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_rm_inventory_active_lot_desc
    ON public.raw_material_inventory (lot_id DESC)
    WHERE remaining_weight > 0;
CREATE INDEX IF NOT EXISTS idx_rm_inventory_material_active_lot_desc
    ON public.raw_material_inventory (raw_material_name, lot_id DESC)
    WHERE remaining_weight > 0;
CREATE INDEX IF NOT EXISTS idx_rm_inventory_material_lot_desc
    ON public.raw_material_inventory (raw_material_name, lot_id DESC);
CREATE INDEX IF NOT EXISTS idx_rm_inventory_purchase_id
    ON public.raw_material_inventory (purchase_id)
    WHERE purchase_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_batch_input_lot_id
    ON public.batch_input (lot_id);
CREATE INDEX IF NOT EXISTS idx_batch_output_batch_id
    ON public.batch_output (batch_id);
CREATE INDEX IF NOT EXISTS idx_batch_output_batch_alloy
    ON public.batch_output (batch_id, alloy_id);
CREATE INDEX IF NOT EXISTS idx_fg_inventory_batch_bundle_desc
    ON public.finished_goods_inventory (batch_id, bundle_id DESC);
CREATE INDEX IF NOT EXISTS idx_fg_inventory_status_batch
    ON public.finished_goods_inventory (finished_goods_status, batch_id)
    WHERE finished_goods_status IN ('Available', 'Under_Testing', 'Assigned');
CREATE INDEX IF NOT EXISTS idx_packing_list_batch_batch_id
    ON public.packing_list_batch (batch_id);
CREATE INDEX IF NOT EXISTS idx_packing_list_po_alloy_status
    ON public.packing_list (customer_po_no, alloy_id, packing_list_status);
CREATE INDEX IF NOT EXISTS idx_purchase_order_open_delivery
    ON public.purchase_order (delivery_date, customer_po_no, alloy_id)
    WHERE purchase_order_status = 'Open';

INSERT INTO public.section_table_permissions
    (section_key, table_name, can_select, can_insert, can_update, can_delete)
SELECT 'overview', table_name, true, false, false, false
FROM unnest(ARRAY[
    'purchase_order','packing_list','packing_list_batch','finished_goods_inventory',
    'production_batch','raw_material_master','raw_material_inventory','alloy_master',
    'furnace_oil_inventory','electricity_consumption','electricity_consumption__lines'
]) AS table_name
ON CONFLICT (section_key, table_name) DO UPDATE SET
    can_select = EXCLUDED.can_select,
    can_insert = EXCLUDED.can_insert,
    can_update = EXCLUDED.can_update,
    can_delete = EXCLUDED.can_delete;

INSERT INTO public.section_table_permissions
    (section_key, table_name, can_select, can_insert, can_update, can_delete)
SELECT 'purchasing', table_name, true, true, true, false
FROM unnest(ARRAY[
    'vendor_master','raw_material_purchase','raw_material_inventory',
    'raw_material_master','raw_material_spec','isri_code_table','purchase_order',
    'customer_master','state_city_master','month_code','element_master','alloy_master',
    'alloy_master_spec','company_profile','finished_goods_inventory','packing_list',
    'packing_list_batch','packing_list_certificate','packing_list_certificate_line',
    'packing_list_certificate_source','packing_list_visual_inspection',
    'packing_list_deviation_letter','build_of_material','production_batch',
    'batch_output','batch_chemical_composition','inventory_movements'
]) AS table_name
ON CONFLICT (section_key, table_name) DO UPDATE SET
    can_select = EXCLUDED.can_select,
    can_insert = EXCLUDED.can_insert,
    can_update = EXCLUDED.can_update,
    can_delete = EXCLUDED.can_delete;

INSERT INTO public.section_table_permissions
    (section_key, table_name, can_select, can_insert, can_update, can_delete)
SELECT 'production', table_name, true, true, true, false
FROM unnest(ARRAY[
    'production_batch','production_supervisor','batch_input','batch_output',
    'batch_chemical_composition','furnace_master','crucible_master','melter_master',
    'trolley_master','alloy_master','alloy_master_spec','element_master',
    'build_of_material','raw_material_inventory','raw_material_master',
    'raw_material_spec','isri_code_table','finished_goods_inventory',
    'company_profile','alloy_data_checker','inventory_movements'
]) AS table_name
ON CONFLICT (section_key, table_name) DO UPDATE SET
    can_select = EXCLUDED.can_select,
    can_insert = EXCLUDED.can_insert,
    can_update = EXCLUDED.can_update,
    can_delete = EXCLUDED.can_delete;

INSERT INTO public.section_table_permissions
    (section_key, table_name, can_select, can_insert, can_update, can_delete)
SELECT 'utilities', table_name, true, true, true, false
FROM unnest(ARRAY[
    'furnace_oil_purchase','furnace_oil_consumption','furnace_oil_inventory',
    'furnace_oil_consumption__daily','electricity_consumption',
    'electricity_consumption__lines','cost_of_conversion','vendor_master',
    'company_profile','inventory_movements'
]) AS table_name
ON CONFLICT (section_key, table_name) DO UPDATE SET
    can_select = EXCLUDED.can_select,
    can_insert = EXCLUDED.can_insert,
    can_update = EXCLUDED.can_update,
    can_delete = EXCLUDED.can_delete;

INSERT INTO public.section_table_permissions
    (section_key, table_name, can_select, can_insert, can_update, can_delete)
SELECT 'masters', table_name, true, true, true, false
FROM unnest(ARRAY[
    'company_profile','customer_master','vendor_master','raw_material_master',
    'raw_material_spec','isri_code_table','alloy_master','alloy_master_spec',
    'element_master','furnace_master','crucible_master','melter_master',
    'trolley_master','state_city_master','month_code'
]) AS table_name
ON CONFLICT (section_key, table_name) DO UPDATE SET
    can_select = EXCLUDED.can_select,
    can_insert = EXCLUDED.can_insert,
    can_update = EXCLUDED.can_update,
    can_delete = EXCLUDED.can_delete;

INSERT INTO public.section_table_permissions
    (section_key, table_name, can_select, can_insert, can_update, can_delete)
SELECT 'admin', table_name, true, true, true, true
FROM unnest(ARRAY[
    'roles','employees','role_permissions','section_table_permissions',
    'inventory_movements','access_matrix','packing_list','packing_list_batch',
    'packing_list_certificate','packing_list_certificate_line',
    'packing_list_certificate_source','packing_list_visual_inspection',
    'finished_goods_inventory'
]) AS table_name
ON CONFLICT (section_key, table_name) DO UPDATE SET
    can_select = EXCLUDED.can_select,
    can_insert = EXCLUDED.can_insert,
    can_update = EXCLUDED.can_update,
    can_delete = EXCLUDED.can_delete;

CREATE OR REPLACE FUNCTION public.nualco_current_role_id()
RETURNS integer
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $fn$
    SELECT e.role_id
    FROM public.employees e
    WHERE lower(e.employee_id) = lower(
        NULLIF(current_setting('nualco.employee_id', true), '')
    )
      AND lower(COALESCE(e.status, 'Active')) = 'active'
    LIMIT 1
$fn$;

CREATE OR REPLACE FUNCTION public.nualco_role_name()
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $fn$
    SELECT lower(COALESCE(r.role_name, ''))
    FROM public.roles r
    WHERE r.role_id = public.nualco_current_role_id()
$fn$;

CREATE OR REPLACE FUNCTION public.nualco_is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $fn$
    SELECT COALESCE(public.nualco_role_name() = 'admin', false)
$fn$;

CREATE OR REPLACE FUNCTION public.nualco_can(p_table text, p_action text)
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $fn$
    SELECT
        public.nualco_is_admin()
        OR EXISTS (
            SELECT 1
            FROM public.role_permissions rp
            JOIN public.section_table_permissions sp
              ON sp.section_key = rp.section_key
            WHERE rp.role_id = public.nualco_current_role_id()
              AND sp.table_name = lower(p_table)
              AND CASE lower(p_action)
                    WHEN 'select' THEN sp.can_select
                    WHEN 'insert' THEN sp.can_insert
                    WHEN 'update' THEN sp.can_update
                    WHEN 'delete' THEN sp.can_delete
                    ELSE false
                  END
        )
$fn$;

CREATE OR REPLACE FUNCTION public.nualco_auth_record(p_employee_id text)
RETURNS TABLE (
    employee_id text,
    first_name text,
    last_name text,
    email text,
    role_id integer,
    role_name text,
    status text,
    password_hash text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $fn$
    SELECT e.employee_id::text, e.first_name::text, e.last_name::text,
           e.email::text, e.role_id, r.role_name::text, e.status::text,
           e.password_hash::text
    FROM public.employees e
    LEFT JOIN public.roles r ON r.role_id = e.role_id
    WHERE lower(e.employee_id) = lower(p_employee_id)
    LIMIT 1
$fn$;

CREATE OR REPLACE FUNCTION public.nualco_bootstrap_admins()
RETURNS TABLE (
    employee_id text,
    first_name text,
    last_name text,
    email text,
    role_id integer,
    role_name text,
    status text
)
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $fn$
    SELECT e.employee_id::text, e.first_name::text, e.last_name::text,
           e.email::text, e.role_id, r.role_name::text, e.status::text
    FROM public.employees e
    JOIN public.roles r ON r.role_id = e.role_id
    WHERE lower(r.role_name) = 'admin'
      AND lower(COALESCE(e.status, 'Active')) = 'active'
      AND NOT EXISTS (
          SELECT 1 FROM public.employees x
          WHERE NULLIF(trim(x.password_hash), '') IS NOT NULL
      )
    ORDER BY e.employee_id
$fn$;

CREATE OR REPLACE FUNCTION public.nualco_passwords_initialized()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $fn$
    SELECT EXISTS (
        SELECT 1 FROM public.employees
        WHERE NULLIF(trim(password_hash), '') IS NOT NULL
    )
$fn$;

CREATE OR REPLACE FUNCTION public.nualco_set_first_admin_password(
    p_employee_id text,
    p_password_hash text
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $fn$
BEGIN
    PERFORM pg_advisory_xact_lock(hashtext('nualco:first-admin-password'));
    IF EXISTS (
        SELECT 1 FROM public.employees
        WHERE NULLIF(trim(password_hash), '') IS NOT NULL
    ) THEN
        RETURN false;
    END IF;
    UPDATE public.employees e
       SET password_hash = p_password_hash,
           password_updated_at = now()
      FROM public.roles r
     WHERE e.role_id = r.role_id
       AND lower(r.role_name) = 'admin'
       AND lower(e.employee_id) = lower(p_employee_id)
       AND lower(COALESCE(e.status, 'Active')) = 'active';
    RETURN FOUND;
END
$fn$;

CREATE OR REPLACE FUNCTION public.nualco_prevent_movement_change()
RETURNS trigger
LANGUAGE plpgsql
SET search_path = pg_catalog, public
AS $fn$
BEGIN
    RAISE EXCEPTION 'inventory_movements is immutable; post a compensating movement';
END
$fn$;

DROP TRIGGER IF EXISTS inventory_movements_immutable
    ON public.inventory_movements;
CREATE TRIGGER inventory_movements_immutable
BEFORE UPDATE OR DELETE ON public.inventory_movements
FOR EACH ROW EXECUTE FUNCTION public.nualco_prevent_movement_change();

REVOKE ALL ON FUNCTION public.nualco_current_role_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.nualco_role_name() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.nualco_is_admin() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.nualco_can(text, text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.nualco_auth_record(text) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.nualco_bootstrap_admins() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.nualco_passwords_initialized() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.nualco_set_first_admin_password(text, text) FROM PUBLIC;

INSERT INTO public.inventory_movements (
    inventory_kind, lot_id, quantity_delta, unit, movement_type,
    source_type, source_id, idempotency_key, occurred_at, reason
)
SELECT 'raw_material', i.lot_id, i.remaining_weight, 'kg', 'opening_balance',
       'migration', '001', 'baseline:raw_material:' || i.lot_id,
       now(), 'Opening balance captured before movement-ledger cutover'
FROM public.raw_material_inventory i
WHERE COALESCE(i.remaining_weight, 0) <> 0
ON CONFLICT (idempotency_key) DO NOTHING;

INSERT INTO public.inventory_movements (
    inventory_kind, bundle_id, batch_id, quantity_delta, unit, movement_type,
    source_type, source_id, idempotency_key, occurred_at, reason
)
SELECT 'finished_goods', fg.bundle_id, fg.batch_id, fg.output_weight, 'kg',
       'opening_balance', 'migration', '001',
       'baseline:finished_goods:kg:' || fg.bundle_id,
       now(), 'Opening balance captured before movement-ledger cutover'
FROM public.finished_goods_inventory fg
WHERE COALESCE(fg.output_weight, 0) <> 0
ON CONFLICT (idempotency_key) DO NOTHING;

INSERT INTO public.inventory_movements (
    inventory_kind, bundle_id, batch_id, quantity_delta, unit, movement_type,
    source_type, source_id, idempotency_key, occurred_at, reason
)
SELECT 'finished_goods', fg.bundle_id, fg.batch_id, fg.output_pieces, 'piece',
       'opening_balance', 'migration', '001',
       'baseline:finished_goods:piece:' || fg.bundle_id,
       now(), 'Opening piece balance captured before movement-ledger cutover'
FROM public.finished_goods_inventory fg
WHERE COALESCE(fg.output_pieces, 0) <> 0
ON CONFLICT (idempotency_key) DO NOTHING;

INSERT INTO public.inventory_movements (
    inventory_kind, quantity_delta, unit, movement_type,
    source_type, source_id, idempotency_key, occurred_at, reason
)
SELECT 'furnace_oil', foi.closing_qty, 'litre', 'opening_balance',
       'migration', '001', 'baseline:furnace_oil',
       now(), 'Opening oil balance captured before movement-ledger cutover'
FROM public.furnace_oil_inventory foi
ORDER BY foi.inventory_date DESC
LIMIT 1
ON CONFLICT (idempotency_key) DO NOTHING;

DO $do$
DECLARE
    t record;
BEGIN
    FOR t IN
        SELECT c.relname
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public'
          AND c.relkind = 'r'
          AND c.relname NOT IN ('schema_migrations')
    LOOP
        EXECUTE format('ALTER TABLE public.%I ENABLE ROW LEVEL SECURITY', t.relname);
        EXECUTE format('ALTER TABLE public.%I FORCE ROW LEVEL SECURITY', t.relname);
        EXECUTE format('DROP POLICY IF EXISTS nualco_all ON public.%I', t.relname);
        EXECUTE format('DROP POLICY IF EXISTS nualco_select ON public.%I', t.relname);
        EXECUTE format('DROP POLICY IF EXISTS nualco_insert ON public.%I', t.relname);
        EXECUTE format('DROP POLICY IF EXISTS nualco_update ON public.%I', t.relname);
        EXECUTE format('DROP POLICY IF EXISTS nualco_delete ON public.%I', t.relname);
        EXECUTE format(
            'CREATE POLICY nualco_select ON public.%I FOR SELECT USING (public.nualco_can(%L, %L))',
            t.relname, t.relname, 'select'
        );
        EXECUTE format(
            'CREATE POLICY nualco_insert ON public.%I FOR INSERT WITH CHECK (public.nualco_can(%L, %L))',
            t.relname, t.relname, 'insert'
        );
        EXECUTE format(
            'CREATE POLICY nualco_update ON public.%I FOR UPDATE USING (public.nualco_can(%L, %L)) WITH CHECK (public.nualco_can(%L, %L))',
            t.relname, t.relname, 'update', t.relname, 'update'
        );
        EXECUTE format(
            'CREATE POLICY nualco_delete ON public.%I FOR DELETE USING (public.nualco_can(%L, %L))',
            t.relname, t.relname, 'delete'
        );
    END LOOP;
END
$do$;

DROP POLICY IF EXISTS nualco_select ON public.employees;
CREATE POLICY nualco_select ON public.employees
FOR SELECT USING (
    public.nualco_is_admin()
    OR lower(employee_id) = lower(
        NULLIF(current_setting('nualco.employee_id', true), '')
    )
);
DROP POLICY IF EXISTS nualco_insert ON public.employees;
CREATE POLICY nualco_insert ON public.employees
FOR INSERT WITH CHECK (public.nualco_is_admin());
DROP POLICY IF EXISTS nualco_update ON public.employees;
CREATE POLICY nualco_update ON public.employees
FOR UPDATE USING (public.nualco_is_admin())
WITH CHECK (public.nualco_is_admin());
DROP POLICY IF EXISTS nualco_delete ON public.employees;
CREATE POLICY nualco_delete ON public.employees
FOR DELETE USING (public.nualco_is_admin());

DROP POLICY IF EXISTS nualco_select ON public.roles;
CREATE POLICY nualco_select ON public.roles
FOR SELECT USING (public.nualco_current_role_id() IS NOT NULL);
DROP POLICY IF EXISTS nualco_insert ON public.roles;
CREATE POLICY nualco_insert ON public.roles
FOR INSERT WITH CHECK (public.nualco_is_admin());
DROP POLICY IF EXISTS nualco_update ON public.roles;
CREATE POLICY nualco_update ON public.roles
FOR UPDATE USING (public.nualco_is_admin())
WITH CHECK (public.nualco_is_admin());
DROP POLICY IF EXISTS nualco_delete ON public.roles;
CREATE POLICY nualco_delete ON public.roles
FOR DELETE USING (public.nualco_is_admin());

DROP POLICY IF EXISTS nualco_select ON public.role_permissions;
CREATE POLICY nualco_select ON public.role_permissions
FOR SELECT USING (
    public.nualco_is_admin()
    OR role_id = public.nualco_current_role_id()
);
DROP POLICY IF EXISTS nualco_insert ON public.role_permissions;
CREATE POLICY nualco_insert ON public.role_permissions
FOR INSERT WITH CHECK (public.nualco_is_admin());
DROP POLICY IF EXISTS nualco_update ON public.role_permissions;
CREATE POLICY nualco_update ON public.role_permissions
FOR UPDATE USING (public.nualco_is_admin())
WITH CHECK (public.nualco_is_admin());
DROP POLICY IF EXISTS nualco_delete ON public.role_permissions;
CREATE POLICY nualco_delete ON public.role_permissions
FOR DELETE USING (public.nualco_is_admin());

INSERT INTO public.schema_migrations(version)
VALUES ('001_harden_supabase')
ON CONFLICT (version) DO NOTHING;

COMMIT;
